### ISSUE TITLE
The testing farm status and log URL is not included in action log

### ISSUE THREAD

**Issue by henrywang** [sclorg/testing-farm-as-github-action#130]
The action log should include testing farm log/result URL (http://artifacts.osci.xxxx.xxx/testing-farm/uuid/). So the test status can be found from that URL. 
```
Run sclorg/testing-farm-as-github-action@v2
  with:
    compose: CentOS-Stream-9
    api_key: ***
    git_url: https://github.com/abc/abc.git
    git_ref: main
    arch: x86_64
    tmt_context: arch=x86_64
    tmt_plan_regex: aws
    tf_scope: private
    secrets: QUAY_USERNAME=***;QUAY_PASSWORD=***;QUAY_SECRET=***;AWS_ACCESS_KEY_ID=***;AWS_SECRET_ACCESS_KEY=***
    variables: TEST_OS=centos-stream-9;ARCH=x86_64;AWS_REGION=us-east-1
    api_url: https://api.dev.testing-farm.io/v0.1
    github_token: ***
    create_issue_comment: false
    pull_request_status_name: Fedora
    update_pull_request_status: false
    create_github_summary: true
    copr: epel-7-x86_64
    environment_settings: {}
    timeout: 480
  env:
    AWS_REGION: us-east-1
```
