### ISSUE TITLE
Document minimal token permissions for succesfully running the Action

### ISSUE THREAD

**Issue by jamacku** [sclorg/testing-farm-as-github-action#87]
### Description

Curent minimal permissions are:

```yml
permissions:
      contents: read
      pull-requests: write
      statuses: write
```
